apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wpdemo
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: wpdemo
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wpdemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wpdemo
spec:
  selector:
    matchLabels:
      app: wpdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wpdemo
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: WORDPRESS_DATABASE_USER
          value: wordpress
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: mysql_us_password
        - name: WORDPRESS_BLOG_NAME
          value: WPDemo Blog
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /bitnami/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
