apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: wpdemo
type: Opaque
data:
  root_password: RGVtbzEyMzQ1IQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app: wpdemo
type: Opaque
data:
  mysql_us_password: RGVtbzEyMzQ1IQ==
